### PR TITLE
Feature/tgz bundle support

### PR DESCRIPTION
**Pull request by zappan**
@virgofx Hi. Here's a PR for the deployment bundle creation as tgz (https://github.com/techpivot/aws-code-deploy/issues/11). Let me know if this works. Thanks

### CODE REVIEW

**Comment by virgofx** [comment]
Looks great. Thanks!

**Comment by zappan** [comment]
@virgofx I can confirm it working.

The only difference between tar and zip is that tar preserves the file ownership in a different way, so on the server I get files unpacked as owned by the user ID from the CI server. But that's not an issue, as ownership change can be done in the deployment script after unbundling

Tar behaviour depends on the user doing the unarchiving, different for root and non-root, and that's by design. What can be done is something like this https://unix.stackexchange.com/questions/278011/anonymous-tarballs when creating the tar archive, setting it to root owner, and then untar will probably take care of it in a way if a non-root user is untaring, it will be set to that user instead of root (as non-root user can't create files in the name of other users).

Leaving all that up to you, as for the general functionality - I confirm it works.

**Comment by virgofx** [comment]
Zappan - Thanks for the confirmation and feedback. Very interesting how the differences in the TAR.  If we potentially add flags for the user/group equal to "root" ... that shouldn't impact actual users/groups on the system at all if they exist or not? But again, I believe AWS code deploy and via scripts in the workflow, the user should be appropriately setting permissions as necessary.

**Comment by zappan** [comment]
I agree that the user can set ownership through the rest of the workflow, I
did that.

I think adding the flags wouldn’t affect actual users/groups in any
practical way, as you don’t expect to have the same user/group on dev or CI
machine and the server.

Flags do set the owner to root when packing the tar, and unpacking the tar
as root would keep the root as the owner, but in case of unpacking as
non-root, ownership would be set to the unpacking user - that’s how I read
the tar documentation, but haven’t tried it out in practice to confirm I
understood the docs correctly.

Also, I can’t really judge what’s a better approach. You might simply leave
it as is, keeping this detail in mind - in case someone opens an issue with
this behaviour and offers a case for the other approach, it’s easy to add
those flags.

**Comment by zappan** [comment]
I agree that the user can set ownership through the rest of the workflow, I did that.

I think adding the flags wouldn’t affect actual users/groups in any practical way, as you don’t expect to have the same user/group on dev or CI machine and the server. 

Flags do set the owner to root when packing the tar, and unpacking the tar as root would keep the root as the owner, but in case of unpacking as non-root, ownership would be set to the unpacking user - that’s how I read the tar documentation, but haven’t tried it out in practice to confirm I understood the docs correctly. 

Also, I can’t really judge what’s a better approach. You might simply leave it as is, keeping this detail in mind - in case someone opens an issue with this behaviour and offers a case for the other approach, it’s easy to add those flags.

**Comment by zappan** [comment]
Actually, thinking from a user perspective, if I download some tar archive and unpack it on my machine, I’d expect the unpacked files to be owned by my current user, and not some non-existing user id.

If we look at it from that side, setting tar files to root for distribution could make sense. If I come across some software packaged as tar file, I’ll check it out from the inside and report how is it packaged and we can take that as a guidance.

**Pull request merged**
